//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int HS_code { get; set; }
        public string HS_address { get; set; }
        public string HS_type { get; set; }
        public decimal HS_price { get; set; }
        public Nullable<byte> HS_nb_rooms { get; set; }
        public Nullable<byte> HS_nb_bathrooms { get; set; }
        public Nullable<bool> HS_garage { get; set; }
        public Nullable<bool> HS_pool { get; set; }
        public Nullable<bool> HS_fireplace { get; set; }
        public int CT_code { get; set; }
    
        public virtual City City { get; set; }
    }
}
